import type { ScenarioConfig } from '@/types/scenario'

export const petScenarios: ScenarioConfig[] = [
  {
    id: 'pet-cat',
    category: 'pet',
    slug: 'cat',
    title: '猫咪',
    emoji: '🐱',
    description: '独立优雅的室友，适合公寓生活与独居青年',
    tagline: '猫的陪伴是安静的奢侈品',
    color: '#f97316',
    lifespan: '12-18年',
    difficulty: '低-中等',
    space: '公寓即可 (30-50㎡)',
    adoption: [
      { id: 'adopt', label: '领养', priceRange: [0, 500], description: '从收容所领养，含基础疫苗' },
      { id: 'buy', label: '购买纯种', priceRange: [3000, 15000], description: '从猫舍购买，含血统证书' },
    ],
    sections: [
      {
        title: '初始装备',
        icon: '🏠',
        items: [
          { label: '猫砂盆', amount: 100, frequency: 'once' },
          { label: '猫抓板/猫爬架', amount: 500, frequency: 'once' },
          { label: '食盆/水盆', amount: 80, frequency: 'once' },
          { label: '猫包/航空箱', amount: 200, frequency: 'once' },
          { label: '玩具礼包', amount: 150, frequency: 'once' },
        ],
      },
      {
        title: '每月开销',
        icon: '💰',
        items: [
          { label: '猫粮 (优质)', amount: 200, frequency: 'monthly' },
          { label: '猫砂', amount: 80, frequency: 'monthly' },
          { label: '零食/罐头', amount: 100, frequency: 'monthly' },
          { label: '驱虫药', amount: 50, frequency: 'monthly', note: '或每3月一次内外驱' },
        ],
      },
      {
        title: '年费固定',
        icon: '🏥',
        items: [
          { label: '年度体检', amount: 500, frequency: 'yearly' },
          { label: '疫苗加强针', amount: 200, frequency: 'yearly' },
          { label: '绝育手术 (一次性)', amount: 800, frequency: 'once', note: '6-8月龄建议' },
        ],
      },
    ],
    timeInvestment: [
      { label: '日常喂食', hoursPerWeek: [1, 2], icon: '🍽️' },
      { label: '铲屎清洁', hoursPerWeek: [1, 2], icon: '🧹' },
      { label: '互动玩耍', hoursPerWeek: [2, 5], icon: '🎾' },
      { label: '健康护理', hoursPerWeek: [0.5, 1], icon: '💊' },
    ],
    totalWeeklyHours: { min: 4.5, max: 10 },
    satisfactionRatings: { joy: 9, growth: 5, social: 4, freedom: 7, meaning: 7, convenience: 9 },
    benefits: [
      { title: '减压神器', description: '撸猫降低皮质醇水平，15分钟即可见效', icon: '😌', impact: 'high' },
      { title: '独居伴侣', description: '独居者的情感慰藉，减少孤独感', icon: '🤗', impact: 'high' },
      { title: '生活习惯', description: '规律喂食倒逼固定作息', icon: '⏰', impact: 'medium' },
    ],
    knowledgeCards: [
      { title: '猫的语言', content: '缓慢眨眼是猫的"亲吻"，代表信任和放松', icon: '😉' },
      { title: '夜行习性', content: '猫是晨昏动物，凌晨和黄昏最活跃，白天睡14-16小时', icon: '🌙', tip: '准备互动玩具消耗精力' },
      { title: '应激反应', content: '搬家、新成员等变化可能引发自发性膀胱炎(FIC)', icon: '⚠️', tip: '使用费洛蒙扩散器辅助安抚' },
    ],
    checklist: [
      '封窗！封窗！封窗！（纱窗算半封）',
      '确认房东/小区允许养宠',
      '离家>3天需安排寄养/自动喂食器',
      '准备至少5000元医疗应急金',
      '百合花等植物对猫有剧毒，须移除',
    ],
    risks: [
      { risk: '尿闭/泌尿疾病', probability: 'medium', mitigation: '多放水碗、湿粮喂养、定期体检' },
      { risk: '抓坏家具', probability: 'high', mitigation: '多设猫抓板、喷拒止剂、定期剪指甲' },
    ],
    funFact: '猫的呼噜声频率在20-140Hz之间，刚好落在促进骨密度恢复的振动频率范围内——这可能是为什么猫受伤后会呼噜。',
  },
  {
    id: 'pet-dog',
    category: 'pet',
    slug: 'dog',
    title: '狗狗',
    emoji: '🐕',
    description: '忠实的户外搭档，需要更多时间与空间投入',
    tagline: '养狗是对快乐最可靠的长期投资',
    color: '#f59e0b',
    lifespan: '10-15年',
    difficulty: '中等-高',
    space: '建议60㎡以上，需外出空间',
    adoption: [
      { id: 'adopt', label: '领养', priceRange: [0, 500], description: '收容所领养混合犬' },
      { id: 'buy', label: '购买纯种', priceRange: [5000, 30000], description: '犬舍购买，含血统证书' },
    ],
    sections: [
      {
        title: '初始装备',
        icon: '🏠',
        items: [
          { label: '狗笼/围栏', amount: 600, frequency: 'once' },
          { label: '牵引绳+项圈', amount: 200, frequency: 'once' },
          { label: '狗窝/垫子', amount: 300, frequency: 'once' },
          { label: '食盆/水盆', amount: 100, frequency: 'once' },
          { label: '玩具/咬胶', amount: 200, frequency: 'once' },
        ],
      },
      {
        title: '每月开销',
        icon: '💰',
        items: [
          { label: '狗粮 (中大型)', amount: 400, frequency: 'monthly' },
          { label: '零食/磨牙棒', amount: 150, frequency: 'monthly' },
          { label: '驱虫药', amount: 100, frequency: 'monthly' },
          { label: '美容洗澡', amount: 200, frequency: 'monthly', note: '小型犬可在家洗' },
        ],
      },
      {
        title: '年费固定',
        icon: '🏥',
        items: [
          { label: '疫苗套餐', amount: 400, frequency: 'yearly' },
          { label: '狗证年审', amount: 300, frequency: 'yearly' },
          { label: '绝育手术', amount: 1500, frequency: 'once', note: '6-12月龄建议' },
        ],
      },
    ],
    timeInvestment: [
      { label: '每日遛狗', hoursPerWeek: [7, 14], icon: '🚶' },
      { label: '喂食饮水', hoursPerWeek: [1, 2], icon: '🍽️' },
      { label: '训练社交', hoursPerWeek: [2, 4], icon: '🎓' },
      { label: '清洁护理', hoursPerWeek: [1, 2], icon: '🛁' },
    ],
    totalWeeklyHours: { min: 11, max: 22 },
    satisfactionRatings: { joy: 10, growth: 7, social: 8, freedom: 3, meaning: 8, convenience: 4 },
    benefits: [
      { title: '运动动力', description: '每天2次遛狗，日均步数自动破万', icon: '🏃', impact: 'high' },
      { title: '社交催化剂', description: '遛狗公园是天然社交场，狗友圈自动形成', icon: '💬', impact: 'high' },
      { title: '安全感', description: '狗狗的警觉性让你独居也心安', icon: '🛡️', impact: 'medium' },
    ],
    knowledgeCards: [
      { title: '分离焦虑', content: '约14%的宠物狗存在分离焦虑，表现为拆家、嚎叫', icon: '😰', tip: '逐步训练独处时间，从5分钟开始' },
      { title: '社会化窗口', content: '3-16周龄是狗狗社会化的黄金期，错过影响一生行为', icon: '🪟' },
      { title: '品种差异', content: '边牧智商≈2-3岁儿童，法斗因呼吸道短需避免高温运动', icon: '🧬' },
    ],
    checklist: [
      '确认小区有遛狗区域或附近有公园',
      '工作日能否保证早晚各一次遛狗？',
      '出差/旅行需安排寄养（约60-120元/天）',
      '办理狗证（需疫苗证明+房东同意书）',
      '学习基础服从性训练（坐、等、来）',
    ],
    risks: [
      { risk: '拆家/破坏', probability: 'high', mitigation: '充足运动+益智玩具+笼内训练' },
      { risk: '咬伤纠纷', probability: 'low', mitigation: '牵引绳+嘴套(如需)+第三者责任险' },
    ],
    funFact: '狗狗能通过气味探测人类情绪变化——恐惧时释放的肾上腺素和皮质醇，狗在几秒内就能嗅到。',
  },
  {
    id: 'pet-rabbit',
    category: 'pet',
    slug: 'rabbit',
    title: '兔兔',
    emoji: '🐰',
    description: '安静温柔的草食伙伴，适合空间有限的城市生活',
    tagline: '最安静的室友，用耳朵说话',
    color: '#ec4899',
    lifespan: '8-12年',
    difficulty: '中等',
    space: '30㎡以上，需笼位+散养区',
    adoption: [
      { id: 'adopt', label: '领养', priceRange: [0, 200], description: '兔友会/收容所领养' },
      { id: 'buy', label: '购买品种兔', priceRange: [500, 3000], description: '垂耳兔、侏儒兔等品种' },
    ],
    sections: [
      {
        title: '初始装备',
        icon: '🏠',
        items: [
          { label: '兔笼 (≥80cm)', amount: 400, frequency: 'once' },
          { label: '兔厕所+底材', amount: 150, frequency: 'once' },
          { label: '草架/水壶', amount: 100, frequency: 'once' },
          { label: '躲避屋', amount: 80, frequency: 'once' },
          { label: '磨牙玩具', amount: 80, frequency: 'once' },
        ],
      },
      {
        title: '每月开销',
        icon: '💰',
        items: [
          { label: '提摩西草', amount: 100, frequency: 'monthly' },
          { label: '兔粮', amount: 80, frequency: 'monthly' },
          { label: '垫材(木粒/纸粒)', amount: 60, frequency: 'monthly' },
          { label: '新鲜蔬菜', amount: 50, frequency: 'monthly' },
        ],
      },
      {
        title: '年费固定',
        icon: '🏥',
        items: [
          { label: '年度体检', amount: 300, frequency: 'yearly' },
          { label: '绝育手术', amount: 1000, frequency: 'once' },
        ],
      },
    ],
    timeInvestment: [
      { label: '喂食换水', hoursPerWeek: [1, 2], icon: '🍽️' },
      { label: '笼舍清洁', hoursPerWeek: [2, 3], icon: '🧹' },
      { label: '放风陪玩', hoursPerWeek: [3, 5], icon: '🐰' },
      { label: '梳毛护理', hoursPerWeek: [0.5, 1], icon: '🪮' },
    ],
    totalWeeklyHours: { min: 6.5, max: 11 },
    satisfactionRatings: { joy: 8, growth: 3, social: 2, freedom: 7, meaning: 5, convenience: 8 },
    benefits: [
      { title: '低噪音', description: '没有吠叫困扰，适合隔音差的公寓楼', icon: '🤫', impact: 'high' },
      { title: '治愈感', description: '看兔子吃草有ASMR般的解压效果', icon: '🌿', impact: 'high' },
      { title: '植物亲和', description: '兔便便是天然有机肥，阳台花草的天堂', icon: '🌱', impact: 'low' },
    ],
    knowledgeCards: [
      { title: '草食主义', content: '兔子的牙齿一生都在生长，必须通过啃草磨牙，否则会刺穿颌骨', icon: '🦷' },
      { title: '胆小敏感', content: '突然的巨响可能导致兔子应激休克甚至死亡', icon: '💥', tip: '避免在兔笼旁开吸尘器/音响' },
      { title: '抱抱禁忌', content: '大多数兔子不喜欢被抱，仰躺会触发僵直反应(假死状态)', icon: '🚫' },
    ],
    checklist: [
      '收纳所有电线（兔子是天然咬线狂）',
      '准备冰垫/冰瓶用于夏季降温（>28°C有中暑风险）',
      '提摩西草无限量供应 > 80%饮食占比',
      '每周至少4次放风（每次1-2小时）',
      '学习判断兔便便健康（大小、硬度、颜色）',
    ],
    risks: [
      { risk: '牙齿过长', probability: 'medium', mitigation: '无限量提供提摩西草+磨牙块' },
      { risk: '消化停滞(GI Stasis)', probability: 'medium', mitigation: '保证粗纤维摄入+即时就医' },
    ],
    funFact: '兔子能看到身后360度（除了正前方一个小盲区），这也是为什么从背后接近兔子它们会弹跳逃开。',
  },
]
